---
- name: Loop through output
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Get file listing
      command: ls -l
      register: lsoutput
    - name: Print file listing
      debug:
        msg: "{{ lsoutput.stdout_lines }}"
    - name: Loop through file listing using with_items
      debug:
        msg: "-------- {{ item }} ----------"
      with_items: "{{ lsoutput.stdout_lines }}"
    - name: Loop through file listing using loop
      debug:
        msg: "++++++++ {{ item }} ++++++++++"
      loop: "{{ lsoutput.stdout_lines }}"

    # command: ls -l | perl -lne '@a = split(" +", $_);print $a[0..4, $#a]'
    # command: perl -lne 'foreach(`ls -l`){@a = split(" +", $_);print $a[0..4, $#a]}'
    # command: perl -lne 'print "Hello World"; print `ls -l`'
    - name: Grab data from command
      command: ls -l
      register: lsoutput
    - name: Loop through data from command listing using loop
      debug:
        msg: "........ {{ item }} .........."
      loop: "{{ lsoutput.stdout_lines }}"


    - script: /home/student/mycode/myls.pl
      args:
        executable: perl
      register: lsoutput
    - name: Loop through data from script listing using loop
      debug:
        msg: "======== {{ item }} =========="
      loop: "{{ lsoutput.stdout_lines }}"

