---
- name: Another network playbook example
  hosts: ~^arista
  gather_facts: no

  tasks:
  - name: Harvest Arista facts
    eos_facts:
    when: ansible_network_os == 'eos'
  - name: Push to the local system
    copy:
      content: "{{ ansible_facts | to_nice_json }}"
      dest: "/home/student/mycode/lab_p114/{{ inventory_hostname }}.txt"
    tags:
      - never
      - grabfacts
  - name: Getting at net interfaces
    debug:
      var: ansible_facts.net_interfaces
